# Generated by Django 4.0.1 on 2022-01-16 08:10

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(default='unknown', max_length=128)),
                ('reply_text', jsonfield.fields.JSONField()),
            ],
        ),
    ]
